# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "senorfy-raspberrypi"
BBFILE_PATTERN_senorfy-raspberrypi := "^${LAYERDIR}/"
BBFILE_PRIORITY_senorfy-raspberrypi = "26"

LAYERSERIES_COMPAT_senorfy-raspberrypi = "dunfell"

